version: '3.8'

services:
  turn-server:
    build: .
    ports:
      - "3478:3478/udp"
      - "3478:3478/tcp"
      - "5349:5349/udp"
      - "5349:5349/tcp"
    environment:
      - TURN_PASSWORD=test-password-123
      - RENDER_EXTERNAL_IP=localhost
    volumes:
      - ./logs:/var/log/coturn
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
